{% set name = "apollinaire" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apollinaire-{{ version }}.tar.gz
  sha256: 81530917605dfd8d30dc16f09bbd92454130f1ef92a471159bf59b988cf96602

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - astropy
    - corner
    - dill
    - emcee
    - george
    - h5py
    - joblib
    - numba
    - numdifftools
    - numpy
    - pandas
    - pathos
    - python >=3.7
    - scipy
    - statsmodels
    - urllib3
    - matplotlib-base
    - tqdm

test:
  imports:
    - apollinaire
    - apollinaire.peakbagging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://apollinaire.readthedocs.io
  summary: Module for helio- and asteroseismic data analysis
  description: |
    Python tools for helioseismic and asteroseismic frameworks. This package
    provides functions and frameworks designed for helioseismic and
    asteroseismic instruments data managing and analysis, especially
    MCMC tools for peakbagging.
  license: CECILL-2.1
  license_file: LICENSE
  doc_url: https://apollinaire.readthedocs.io/
  dev_url: https://gitlab.com/sybreton/apollinaire

extra:
  recipe-maintainers:
    - sybreton
