{% set name = "apollinaire" %}
{% set version = "1.3.2" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apollinaire-{{ version }}.tar.gz
  sha256: 0e81d332dcec280e2d3b39ac489bb3b55a4c0bed42f678e9ea9840988c6d35d8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - astropy-base
    - corner
    - dill
    - emcee
    - george
    - h5py
    - joblib
    - numba
    - numdifftools
    - numpy
    - pandas
    - pathos
    - scipy
    - statsmodels
    - urllib3
    - matplotlib-base
    - tqdm

test:
  imports:
    - apollinaire
    - apollinaire.peakbagging
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://apollinaire.readthedocs.io
  summary: Module for helio- and asteroseismic data analysis
  description: |
    Python tools for helioseismic and asteroseismic frameworks. This package
    provides functions and frameworks designed for helioseismic and
    asteroseismic instruments data managing and analysis, especially
    MCMC tools for peakbagging.
  license: CECILL-2.1
  license_file: LICENSE
  doc_url: https://apollinaire.readthedocs.io/
  dev_url: https://gitlab.com/sybreton/apollinaire

extra:
  recipe-maintainers:
    - sybreton
